version: '2.1'

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.10.1
      docker_layer_caching: true
    steps:
      - checkout
      - run: apt list --installed
#      - run: ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true --stacktrace
