version: '2.1'

executors:
  openjdk-21:
    docker:
      - image: cimg/openjdk:21.0.2
    resource_class: arm.medium

jobs:
  build:
    executor: openjdk-21
    steps:
      - checkout
      - run: ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
