version: '2.1'

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.10.1
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Install OpenJDK 21
          command: |
            sudo apt-get update && sudo apt-get install openjdk-21-jdk
#      - run: ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true --stacktrace
