version: '2.1'
jobs:
  build:
    machine:
      image: ubuntu-2004:2023.10.1
    resource_class: arm.medium
    steps:
      - checkout
      - run: ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
workflows:
  build:
    jobs:
      - build